apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd-client
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: client
    protocol: TCP
    port: {{ .Values.servicePorts.client }}
    targetPort: {{ .Values.servicePorts.client }}
  - name: server
    protocol: TCP
    port: {{ .Values.servicePorts.server }}
    targetPort: {{ .Values.servicePorts.server }}
